#!/bin/bash
echo "Listing the files in the repo."
ls -al
echo "+++++++++++++++++++++++++++++++++++++++++"
packer build -var 'aws_access_key=XXXXXXXXXXXXXXXXXX' -var 'aws_secret_key=YYYYYYYYYYYYYYYYYYYYYYY' packer.json
echo "+++++++++++++++++++++++++++++++++++++++++"
terraform init
terraform apply --var-file terraform.tfvars -var='aws_access_key=XXXXXXXXXXXXXXXXXX' -var='aws_secret_key=YYYYYYYYYYYYYYYYYYYYYYY' --auto-approve
echo "SUCCESS"
